[package]
name = "quad2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
=======
num = "0.4.0"
>>>>>>> f755e77 (added both single and multithreaded + fixed only negative root generation)
rand = "0.8.5"
rayon = "1.7"
